### ISSUE TITLE
Run on Macos?

### ISSUE THREAD

**Issue by ghost** [larrybahr/windows-network-drive#11]
Any chance that this can be configured for MacOs? I am currently trying to build a tool that will allow me to connect to a windows shared drive from my mac (finder is absolute garbage for connecting to shared drives) and whenever I run your package on a mac I get the error "windows-network-drive can only run on windows."

**Comment by larrybahr** [comment]
There is a [port of this for MacOs called mac-network-drive](https://www.npmjs.com/package/mac-network-drive) that might work for you.
Since this is a Windows specific lib I do not plan to support Mac directly. At some point I would like to try to merge the Mac/Linux network mounting code into one solution so there is a single package that can be used on all the platforms.
