### ISSUE TITLE
Issue with finding an extended drive path when a shorter one already exists

### ISSUE THREAD

**Issue by ghost** [larrybahr/windows-network-drive#2]
I found what I believe to be an issue.
When part of a network drive path is already mapped to a drive... for example:

\\\\something\\at\\ mapped to drive Z

If I do:

```
const networkDrive = require('windows-network-drive');
let networkDrivePath = '\\\\something\\at\\something\\at';
let networkDriveLetter = 'F';

networkDrive.find(networkDrivePath).then(function(driveLetter) {
    // driveLetter will = []
});
```

For some reason, it will return '' for a drive letter.
To get around this I simply do an if statement inside the find:

```
networkDrive.find(networkDrivePath).then(function(driveLetter) {
    if (driveLetter == '') {
        // then mount it
    }
});
```

Not entirely sure if it's just me though.

**Comment by larrybahr** [comment]
Thank you for submitting an issue. If I am understanding you correctly, then I think this may be a honest mistake in usage and not a bug.

**The Issue**
find() is documented to return an array not a string. In your example it should return an empty array (i.e. []) because the exact path is not mounted. Empty array is truthy when tested for equality to empty string, so your if block is true if it could not find the path. If you use an identity comparison (i.e. `if (driveLetter === '')`) instead of an equality comparison (i.e. `if (driveLetter == '')`) then it will not work because === checks the type.

**The Test**
To test this you can run:
```javascript
const VALID_MOUNT_PATH = "\\\\something\\at";
const VALID_MOUNT_CHILD_PATH = VALID_MOUNT_PATH + "\\something\\at";
let networkDrive = require('windows-network-drive');
let driveLetter;
let foundDriveLetters;

return Promise.resolve()
	.then(function ()
	{
		return networkDrive.mount(VALID_MOUNT_PATH);
	})
	.then(function (result)
	{
		driveLetter = result;
		return;
	})
	.then(function ()
	{
		return networkDrive.find(VALID_MOUNT_CHILD_PATH);
	})
	.then(function (result)
	{
		foundDriveLetters = result;
		return;
	})
	.then(function ()
	{
		/**
		 * Clean up the mounted drive path
		 */
		return networkDrive.unmount(driveLetter);
	})
	.then(function ()
	{
		console.log('found = "' + JSON.stringify(foundDriveLetters) + '" mount = "' + driveLetter + '"');
		console.dir(Array.isArray(foundDriveLetters)); // Make sure find is returning an array as documented
		console.dir(-1 == foundDriveLetters.indexOf(driveLetter)); // Make sure the drive letter is not in the list of returned drive letters
		console.dir([] == ''); // An example of the issue
		return;
	});
```

If it prints true three times then this is most likely your problem.
Example output:
```
found = "[]" mount = "J"
true
true
true
```

**The Solution**
Instead of `if (driveLetter == '')` use `if (0 === driveLetter.length)` because you want to mount the path if it has not been mounted yet.

If I am miss understanding your issue, please post a complete test script I can use to see the issue.

**Comment by ghost** [comment]
@larrybahr Thank you for your response. It turns out it was just me using it wrongly. I thought when the drive could not be found it would return an error. I don't know why I thought this, but after some tests I realize it returns a blank array whenever it can't be found instead of an error. My mistake.
