### ISSUE TITLE
Question: Unit tests

### ISSUE THREAD

**Issue by nytamin** [larrybahr/windows-network-drive#26]
While working on my [previous PR](https://github.com/larrybahr/windows-network-drive/pull/25), I noticed that the test is running actual commands on the machine to achieve the test result.

I was wondering if you are open with rewriting/complementing the tests to be standalone unit tests (ie where the `net use` command is mocked)?

There are a few pros - as I see them - would be:

* The tests are not dependent of the state of the local machine (the existing test require you to clear any existing network drives, otherwise they'll fail)
* The `net use` command returns different results depending on the locale/system language. A unit test would have greater coverage, since tests could run for multiple locales.
* Unit tests would be platform-agnostic (ie can be run in a linux-container)

I've had quite good experience with using Jest for mocks and tests, so I would propose:

* Add new unit-tests, using Jest as test runner. Run these with `npm test`.
* Rename the existing test to integration-test, and run it with `npm integration-test`.

I won't be able to commit to a fixed time plan, but I'll likely be able to trickle in some commits during the next few weeks/months, if you are open to the idea?

**Comment by nytamin** [comment]
For reference, here's an example of a Jest-based test I made in another project (for a temporary workaround pre version 4.0.0):

* [A test](https://github.com/nrkno/sofie-package-manager/blob/df4c732c1b671491d3a6f57ac83c7cf1861a07f5/shared/packages/worker/src/__tests__/fileShare.spec.ts#L4)
* [A mock for `net use`](https://github.com/nrkno/sofie-package-manager/blob/df4c732c1b671491d3a6f57ac83c7cf1861a07f5/tests/internal-tests/src/__mocks__/child_process.ts#L191)

**Comment by larrybahr** [comment]
I think that is a great idea! A very minor thought, I would prefer if the commands to run them would be as follows:
- `test:unit` = unit tests
- `test:integration` = integration tests
- `test` = run both set of tests. I think this would be ideal because if people just want to run the default I would prefer it run both sets before they commit changes.

I know this can be a big undertaking so I am good with doing this over multiple PRs as you have time. E.g. rename the tests now with a single integration test (just so they are not empty) and then add more over time.

I really appreciate all the time you have put into this repo recently. I haven't had time to touch it in a while, but I have a small list of changes I would love to add soon.
