### ISSUE TITLE
GNU/Linux and OS X support

### ISSUE THREAD

**Issue by sentbyravens** [larrybahr/windows-network-drive#6]
Hello!
1st of all, thank you for 3.0.0 release: now I can remove it from "optionalDependencies" and add it right to 'dependencies". :)
But maybe in the future will you support OS X and/or GNU/Linux?
Right now I'm able to add network drive by the hand through one of options:
![Screenshot from 2019-07-23 16-27-52](https://user-images.githubusercontent.com/11899659/61716484-ecf18a00-ad67-11e9-8960-5e9554fb1f20.png)
If you are not going to support these operating systems, then for what reason?
Thanks!

**Comment by larrybahr** [comment]
I do not plan to add Linux or Mac support because it goes out of scope for this package. The purpose is for mounting drives in Windows not SAMBA (Windows share) on other OSs. You can check out https://www.npmjs.com/package/mac-network-drive. It is a Mac port of this package. I do not own a Mac so I have no idea how well it works.
