### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by spearmootz** [larrybahr/windows-network-drive#7]
Sorry, i actually dont use your package but wanted to pose a question to see if you ever ran into the problem i have.

I have a mounted drive on windows that nodejs can access but when i try to read or move files it randomly says the file does not exist.  It does not do it all the time, usually pm2 restarts the process and finishes processing the files successfully.

any insight?

**Comment by larrybahr** [comment]
I am closing this issue since it is not an issue with this package.

I have not had any issues like that. My guess is that multiple processes are manipulating the file at the same time.

E.g.
1. process 1 renames the file or something like that
1. process 2 errors when trying to read the file that process 1 temporarily renamed
1. process 1 finishes and restores the original file name
1. process 2 is restarted and can now access the file
